### PR TITLE
Color even if PlaceholderAPI

### LINKED ISSUE #490: 번지코드 업데이트 이후 색깔 메세지가 안나오는 현상
**Describe the bug/버그 증상**
BungeeCord를 1636에서 1653버전으로 업데이트하니 TriggerReactor 플러그인에서 출력하는 색깔 메세지가 표시되지 않습니다.
(MC 1.18.2 > 1.19 버전 변화에 따른 문제로 예상됨)
ex)
#MESSAGE "&aTEST"를 출력하면 그냥 "&aTEST"로 출력됩니다.
사용중인 플러그인 중 TriggerReactor만 이런 현상이 나와 문의합니다.

**Server information/서버 정보**
1. Spigot/Paper/Bukkit/etc... version/사용중인 서버 버전:
git-Paper-386 (MC: 1.18.2) (Implementing API version 1.18.2-R0.1-SNAPSHOT) (Git: 072f54c on ver/1.18.2)
2. TriggerReactor version/사용중인 트리거 버전:
3.2.5

### PR DESCRIPTION
**Pull request by soshimee**
(Hopefully) fixes #490

### CODE REVIEW

**Comment by wysohn** [comment]
Thank you for your contribution!

**Review by wysohn — APPROVED** [review]

**Comment by soshimee** [comment]
I cannot merge because the workflow hasn't been approved.

**Review by Sayakie — APPROVED** [review]

**Comment by Sayakie** [comment]
I'd do. Thank you for your contribution and be sure to merge into `development` instead of `master` the next time!

**Comment by soshimee** [comment]
Didn't see `development`, thank you for telling me.

**Pull request merged**
