### PR TITLE
fix: Inconsistent behavior of literal string "true"/"false"

### PR DESCRIPTION
**Pull request by Sayakie**
Fixes:
  - #471
  - #472

### CODE REVIEW

**Comment by wysohn** [comment]
Thank you! I will look into it soon

**Comment by wysohn** [comment]
@Sayakie 
Can you also write a unit test for it? That would be awesome!

**Comment by Sayakie** [comment]
@wysohn I've added unit test for it! 🎉

**Review by wysohn — APPROVED** [review]
Indeed, should have checked if it's an ID token before checking the value

Great catch!

Looking good to me

**Pull request merged**
