### PR TITLE
area for minecart

### PR DESCRIPTION
**Pull request by chickiyeah**

### CODE REVIEW

**Comment by chickiyeah** [comment]
> Is there a reason for separating the case of one passenger and several passengers?

It's a phrase that responds to more than one person riding other than Minecart.

**Comment by chickiyeah** [comment]
@Kuiprux If it's deemed unnecessary, I'll delete it.

**Review by Kuiprux — COMMENTED** [review]
I reckon line 242 to 267 with line 215 inside the for statements would cover the whole case. Could you try checking if it works?

**Comment by chickiyeah** [comment]
ok it's unnecessary, I'll delete it.

**Comment by chickiyeah** [comment]
@Kuiprux deleted

**Comment by wysohn** [comment]
@chickiyeah 
Thanks for the great works!

But please revise your branch to have only specific commits per pull request.

It seems your branch has multiple different implementations, and that is not recommended.

Create a new branch out of this branch to back up your changes, and reset your current branch to 8fdbc8e (or up to any point where only the relevant commits are in) so that the pull request only contains the necessary commits.

**Pull request closed without merging**
