### PR TITLE
Fix #436 - CATCH statement only execute first line.

### LINKED ISSUE #436: CATCH statement only execute first line.
Example
```
TRY
    err.cause()        // throwing error
CATCH e
    #LOG "First Line."
    #LOG "Second Line."
ENDTRY
```

Except Output:
> `> First Line.`
> `> Second Line.`

Actual Output:
> `> First Line.`

### PR DESCRIPTION
**Pull request by Ioloolo**
Before:
```
CATCHBODY
  ID   // for saving error
  ...
```

After:
```
CATCHBODY
  ID   // for saving error
  BODY
    ...
```

### CODE REVIEW

**Review by wysohn — COMMENTED** [review]
Test code for this would be nice to have (since we just found the new edge case)

**Comment by Ioloolo** [comment]
BRB

**Review by wysohn — CHANGES_REQUESTED** [review]
Sorry for asking a lot, but do you mind separating all the test cases per method for best practice?

You can take a look at the sample here: https://github.com/TriggerReactor/TriggerReactor/blob/e950ce47be6c140903197b55cfd101b8a1b9d775/core/src/test/java/io/github/wysohn/triggerreactor/core/script/interpreter/TestInterpreter.java#L690 and https://github.com/TriggerReactor/TriggerReactor/blob/e950ce47be6c140903197b55cfd101b8a1b9d775/core/src/test/java/io/github/wysohn/triggerreactor/core/script/interpreter/TestInterpreter.java#L721

Highly recommend to use `mock(Executor.class)` to create a mock version of Executor and test it with `verify()`

**Review by wysohn — APPROVED** [review]
Really appreciated!

Thank you for cleaning up the codes!

**Comment by Ioloolo** [comment]
I want to do clean code continuously, but it's not easy.

Anyway, thank you.

**Comment by wysohn** [comment]
> I want to do clean code continuously, but it's not easy.
> 
> Anyway, thank you.

Indeed, and IMO it's an invaluable skill that you can write codes that's readable

**Pull request merged**
