### PR TITLE
Implemented getslot placeholder for sponge

### PR DESCRIPTION
**Pull request by Kuiprux**

### CODE REVIEW

**Review by wysohn — CHANGES_REQUESTED** [review]
Awesome! The code looks clean.

can you please use 4 spaces instead of tabs though?

Thank you!

**Comment by Kuiprux** [comment]
But it seems that some other placeholders are using tabs. Shall I make them all use 4 spaces?

**Comment by wysohn** [comment]
> But it seems that some other placeholders are using tabs. Shall I make them all use 4 spaces?

Yes, the convention is 4 spaces, but the existing codes are written quite a long time ago, so it's a mess right now.

**Review by wysohn — APPROVED** [review]
wow thank you!

**Comment by wysohn** [comment]
@Kuiprux 
As a last request, can you add your name to the author list in the build.gradle?

**Pull request merged**
