### PR TITLE
refactor: let permit lowercase keywords

### PR DESCRIPTION
**Pull request by Sayakie**
This pull request allows to use lowercase keywords. e.g) `if`, `while`, `switch`, `for`, etc.

---
Download the jar for this pull request: [TriggerReactor-612.zip](https://nightly.link/TriggerReactor/TriggerReactor/actions/artifacts/1000247817.zip)

### CODE REVIEW

**Comment by Cupelt** [comment]
I think this is PR that is less consistent with TR code.
because, The reason is that the basic repertoire of TR codes is as follows.
```
IF a > b
    ...some code
ENDIF
```

But with lowercase letters, you have to rely only on Tab for code separation.
Some people don't actually use the tab.
```
if a > b
    ...some code
endif
```

I don't really know, but it's a different part from the existing TR direction, so I think we need to think carefully.

**Comment by wysohn** [comment]
> I think this is PR that is less consistent with TR code. because, The reason is that the basic repertoire of TR codes is as follows.
> 
> ```
> IF a > b
>     ...some code
> ENDIF
> ```
> 
> But with lowercase letters, you have to rely only on Tab for code separation. Some people don't actually use the tab.
> 
> ```
> if a > b
>     ...some code
> endif
> ```
> 
> I don't really know, but it's a different part from the existing TR direction, so I think we need to think carefully.

I think this and the PR both make sense

Maybe it's time to create a coding convention for our community to avoid confusion

Any ideas? As you mentioned, if keywords are used with lower cases, the following codes must be tabbed, etc.

**Comment by Sayakie** [comment]
Why do we depend on tabbing for code separation? Do you know if whitespaces doesn't work?

**Comment by Cupelt** [comment]
> Why do we depend on tabbing for code separation? Do you know if whitespaces doesn't work?

I meant that the boundaries of IF statements and general codes become ambiguous.

**Comment by wysohn** [comment]
And any resolution on this? @Sayakie @Cupelt

**Comment by Cupelt** [comment]
> And any resolution on this? @Sayakie @Cupelt 

What do you think about having lowercase letters function differently?

like a lambda
```
if b == a => #MESSAGE "a eqals b"
```

**Comment by Sayakie** [comment]
We have to leave it to end-users do determine theirselves. Linting is great supporting tool but why should enforce do?

**Comment by wysohn** [comment]
Unless otherwise no comments from @Cupelt, I will merge this next week

**Pull request merged**
