### PR TITLE
area with minecart

### PR DESCRIPTION
**Pull request by chickiyeah**

### CODE REVIEW

**Comment by chickiyeah** [comment]
@wysohn

**Comment by wysohn** [comment]
Looking good! I will take a look soon

**Comment by rkdrns4747** [comment]
@chickiyeah @wysohn 

Actually, I'm not sure if this is right way with **'stability'.**
We are already listening PlayerMoveEvent to check if a player ENTER/LEAVE an area, which can take up lots of server ticks based on player count.
But we also listen VehicleMoveEvent as internal code, this could become high stabilization vulnerability for AreaTrigger. Furthermore, unlike PlayerMoveEvent, VehicleMoveEvent occurs without player, which also cause problem.

This is just my opinion. What do you guys think 'bout this?

**Comment by wysohn** [comment]
> @chickiyeah @wysohn
> 
> Actually, I'm not sure if this is right way with **'stability'.**
> We are already listening PlayerMoveEvent to check if a player ENTER/LEAVE an area, which can take up lots of server ticks based on player count.
> But we also listen VehicleMoveEvent as internal code, this could become high stabilization vulnerability for AreaTrigger. Furthermore, unlike PlayerMoveEvent, VehicleMoveEvent occurs without player, which also cause problem.
> 
> This is just my opinion. What do you guys think 'bout this?

That's an interesting point that VehicleMoveEvent will be fired even without the player onboard.

I think the most overhead is from the `getAreaForLocation` and it works pretty well for players, yet I am not sure about the vehicles since players can spawn them a lot.

We definitely have to test this. If anyone find something interesting, let me know

**Comment by chickiyeah** [comment]
Why don't we create an option for the vehicle so you can turn it on and on?

**Comment by chickiyeah** [comment]
@rkdrns4747

**Comment by rkdrns4747** [comment]
Still, That cannot solve the problem. As @wysohn said, `getAreaForLocation()` method takes most resources during the process. What this means is that even though we add specific option like `vehicle_analyze: true` on each AreaTrigger's option yaml, its flow still has location-based detecting progression.

It's like:
listen VME -> check if player is in -> **check if the movement is related to specific area and get the area** -> check if the area's setting of `vehicle_analyze` -> ... -> run the trigger

As you can see, setting check is always processed after getting an area, which means it still needs much resource.

However, if the setting is on config.yml, which means its on/off affects all of AreaTriggers, we can turn off vehicle detection on start of plugin with not registering the listener. This also can be a solution.

**Comment by wysohn** [comment]
@chickiyeah 
To be honest, we never know until we perform the stress testing.

I suggest you try your implementation with multiple vehicles (like hundreds or thousands of minecarts) and see how it works using the timings report.

**Comment by rkdrns4747** [comment]
@wysohn 's right. It's just my speculation, and There's no one who tested it.

**Comment by chickiyeah** [comment]
@wysohn ok i will test that

**Comment by chickiyeah** [comment]
@wyshon @rkdrns4747
https://timings.aikar.co/?id=a65861ef22694f99991c966c6fce6277

**Comment by chickiyeah** [comment]
캡처

**Comment by chickiyeah** [comment]
java version "11.0.11" 2021-04-20 LTS
Java(TM) SE Runtime Enviroment 18.9 (build 11.0.11+9-LTS-194)
Java HotSpot(TM) 64-Bit Server VM (18.9 build 11.0.11+9-LTS-194, mixed mode)

@echo off
java -Xms4G -Xmx4G -server -XX:+UseG1GC -XX:+ParallelRefProcEnabled -XX:MaxGCPauseMillis=200 -XX:+UnlockExperimentalVMOptions -XX:+DisableExplicitGC -XX:+AlwaysPreTouch -XX:G1NewSizePercent=30 -XX:G1MaxNewSizePercent=40 -XX:G1HeapRegionSize=8M -XX:G1ReservePercent=20 -XX:G1HeapWastePercent=5 -XX:G1MixedGCCountTarget=4 -XX:InitiatingHeapOccupancyPercent=15 -XX:G1MixedGCLiveThresholdPercent=90 -XX:G1RSetUpdatingPauseTimePercent=5 -XX:SurvivorRatio=32 -XX:+PerfDisableSharedMem -XX:MaxTenuringThreshold=1 -Dusing.aikars.flags=https://mcflags.emc.gs -Daikars.new.flags=true -jar spigot.jar nogui
pause

test on 4G

**Comment by chickiyeah** [comment]
more test result soonn..

**Comment by chickiyeah** [comment]
@rkdrns4747 getAreaForLocation() 
ends without reaching that phrase unless the player is on board

**Comment by rkdrns4747** [comment]
> Still, That cannot solve the problem. As @wysohn said, `getAreaForLocation()` method takes most resources during the process. What this means is that even though we add specific option like `vehicle_analyze: true` on each AreaTrigger's option yaml, its flow still has location-based detecting progression.
> 
> It's like:
> listen VME -> check if player is in -> **check if the movement is related to specific area and get the area** -> check if the area's setting of `vehicle_analyze` -> ... -> run the trigger
> 
> As you can see, setting check is always processed after getting an area, which means it still needs much resource.
> 
> However, if the setting is on config.yml, which means its on/off affects all of AreaTriggers, we can turn off vehicle detection on start of plugin with not registering the listener. This also can be a solution.

@chickiyeah I already mentioned that player check is before the getAreaForLocation()

What I said in that comment was that it's impossible to solve the problem by adding vehicle_analyze option on specific AreaTrigger.

**Comment by wysohn** [comment]
Based on the timings, it doesn't look that bad. 

Probably, as chickiyeah already mentioned, only the vehicles with the passenger will be detected, so that's where the magic happens I assume.

Ofc, we still don't know what happens when each vehicle has players in it, yet I think it's not a great concern atm.

**Comment by rkdrns4747** [comment]
looks not that bad, why don't we release some beta form for this so that users can test if this is actually lagging?

**Comment by chickiyeah** [comment]
sorry im late im testing with villager with changed code

**Comment by chickiyeah** [comment]
@wysohn @rkdrns4747 ITS TOOOO BAD CODEEEE

**Comment by chickiyeah** [comment]
SEE THIS https://timings.aikar.co/?id=1fa325ae3bb44a4580cd9412c0842d9f

**Pull request merged**
