### PR TITLE
Detect minecarts in AreaTrigger

### PR DESCRIPTION
**Pull request by wysohn**

### CODE REVIEW

**Comment by wysohn** [comment]
@chickiyeah 
Do you mind re-doing the stress testing with this implementation?

Many thanks!

**Comment by chickiyeah** [comment]
@wysohn ok re-doing test soon

**Comment by chickiyeah** [comment]
@wysohn https://timings.aikar.co/?id=10c93a36cd3a47288ae97f2ac84aa893

**Comment by chickiyeah** [comment]
캡처

**Comment by wysohn** [comment]
@chickiyeah 
Nicely done!

Was there area triggers working atm? Maybe timings for the trigger itself could be helpful.

`/trg timings`

the VehicleMoveEvent itself doesn't seem to cause many lags, yet I see that the AreaTriggerManager is spending some time when PlayerBlockLocationEvent is fired (by the new implementation)

So once we find that out, we can decide if we add this to the next version

**Comment by chickiyeah** [comment]
[2.txt](https://github.com/TriggerReactor/TriggerReactor/files/6681672/2.txt)
@wysohn

**Comment by wysohn** [comment]
> [2.txt](https://github.com/TriggerReactor/TriggerReactor/files/6681672/2.txt)
> @wysohn

Thanks! Is the trigger on sync mode?

**Comment by chickiyeah** [comment]
[sync.txt](https://github.com/TriggerReactor/TriggerReactor/files/6681686/sync.txt)
@wysohn this file is sync

**Comment by wysohn** [comment]
@chickiyeah 
Yup it seems to be okay 'in my opinion'

Great work!

**Pull request merged**
