### PR TITLE
fix "this.interpreter is null" when an inventory trigger has just been created

### PR DESCRIPTION
**Pull request by Cupelt**

### CODE REVIEW

**Review by wysohn — APPROVED** [review]
Thank you!

**Comment by wysohn** [comment]
@Cupelt Feel free to merge when you are ready

**Review by Sayakie — APPROVED** [review]

**Comment by Cupelt** [comment]
@wysohn Can I merge?

**Comment by wysohn** [comment]
@Cupelt 
You should now have merge access so try it in the future PRs

Let me know otherwise

**Pull request merged**
